---
- name: 플레이북
  hosts: all
  becmoe: true 
  tasks: 
    - name: httpd installation 
      yum: 
      name: httpd 
      state: present 

    - name: stop firewalld 
      service: 
        name: firewalld 
        state: stopped 
        enable: false 

    - name: start and enable httpd 
      service: 
        name: httpd 
        state: started 
        enabled: true
